/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.27
 * Generated at: 2018-03-13 04:58:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class MemberDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/member/../../footer.html", Long.valueOf(1520916976233L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Member member = (Member)request.getAttribute("member");
	
	//취미 처리
	String[] hobbies = member.getHobby().split(",");
	String[] checked = new String[9];
	for(String s : hobbies) {
		switch(s) {		
		case "game": checked[0] = "checked"; break;
		case "reading": checked[1] = "checked"; break;
		case "music": checked[2] = "checked"; break;
		case "climb": checked[3] = "checked"; break;
		case "sport": checked[4] = "checked"; break;
		case "movie": checked[5] = "checked"; break;
		case "travel": checked[6] = "checked"; break;
		case "cook": checked[7] = "checked"; break;
		case "etc": checked[8] = "checked"; break;
		}
	}
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>MemberDetailView</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/first/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t \r\n");
      out.write("\t   $('input[type=password]').blur(function(){\t\t   \r\n");
      out.write("\t\t   console.log(\"포커스 벗어남.\");\r\n");
      out.write("\t\t   var pwd1 = $(\"#upwd\").val();\r\n");
      out.write("\t\t   var pwd2 = $(\"#upwd2\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(pwd1 == pwd2) {\t\t\t\r\n");
      out.write("\t\t\t$(\"#confirm\").css(\"display\",\"true\");\r\n");
      out.write("\t\t\t$(\"#confirm\").val(\"일치\");\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#confirm\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t$(\"#confirm\").val(\"불일치\");\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t   \r\n");
      out.write("\t   }); \t   \r\n");
      out.write("});  \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h2 align=\"center\">내 정보 보기 페이지</h2>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"/first/mupdate\" method=\"post\">\r\n");
      out.write("\t\t<!-- 상대경로 : ../../minsert -->\r\n");
      out.write("\t\t<table width=\"650\" align=\"center\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">아이디</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"userid\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print( member.getUserId() );
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">이름</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"username\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print( member.getUserName() );
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">암 호</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"userpwd\" id=\"upwd\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print( member.getUserPwd() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">암호확인</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" id=\"upwd2\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print( member.getUserPwd() );
      out.write("\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">암호확인 메세지</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"confirm\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\treadonly></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">성 별</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t");
 if(member.getGender().equals("M")) { 
      out.write(" <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\tname=\"gender\" value=\"M\" checked>남 &nbsp; <input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" name=\"gender\" value=\"F\">여 ");
 } else { 
      out.write(" <input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" name=\"gender\" value=\"M\">남 &nbsp; <input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" name=\"gender\" value=\"F\" checked>여 ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">나 이</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"number\" name=\"age\" min=\"20\" max=\"100\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print( member.getAge() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">이메일</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"email\" name=\"email\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print( member.getEmail() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">전화번호</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"tel\" name=\"phone\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print( member.getPhone() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">취 미</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"game\" ");
      out.print( checked[0] );
      out.write(">게임</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"reding\" ");
      out.print( checked[1] );
      out.write(">독서</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"music\" ");
      out.print( checked[2] );
      out.write(">음악</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"climb\" ");
      out.print( checked[3] );
      out.write(">등산</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"sport\" ");
      out.print( checked[4] );
      out.write(">운동</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"movie\" ");
      out.print( checked[5] );
      out.write(">영화</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"travel\" ");
      out.print( checked[6] );
      out.write(">여행</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"cook\" ");
      out.print( checked[7] );
      out.write(">요리</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"etc\" ");
      out.print( checked[8] );
      out.write(">기타</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\">특이사항</th>\r\n");
      out.write("\t\t\t\t<td><textarea name=\"etc\" rows=\"3\" cols=\"50\">");
      out.print( member.getEtc() );
      out.write("</textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<th width=\"150\" colspan=\"2\"><input type=\"submit\" value=\"수정하기\">\r\n");
      out.write("\t\t\t\t\t&nbsp; <a href=\"/first/mdelete?userid=");
      out.print( member.getUserId() );
      out.write("\">탈퇴하기</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"/first/index.jsp\">시작페이지로</a></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\th5 {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tbackground : navy;\r\n");
      out.write("\t\tcolor : white;\r\n");
      out.write("\t\twidth : 80%;\r\n");
      out.write("\t\theight : 70px;\r\n");
      out.write("\t\tpadding-top : 15px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h5 align=\"center\">copyright@2018.03.13 kh.org<br>\r\n");
      out.write("\ttel : 02-1234-5678 &nbsp; &nbsp;\r\n");
      out.write("\tfax : 02-1234-5678\r\n");
      out.write("\t</h5>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
